sql/src/cleanup.cc
=> Erreur de nom de champ - SQL

core/src/multiplexing/muxer.cc
The subscriber lock is now only locked when acknowledging more
than 0 events. For transaction-based endpoints (SQL, storage),
this should increase performance.
=> fix(multiplexing): improve event acknowledgement performance.

influxdb/src/factory.cc
=> Default value error

doc/exploit/stream_connectors.rst
TUD made several changes in the stream connectors documentation.
=> doc(stream connectors): Doc enhanced.

doc/exploit/stream_connectors.rst, lua/src/broker_cache.cc, lua/src/broker_utils.cc, lua/src/factory.cc, lua/test/lua.cc
A new lua method to access the cache that can be useful: get_index_mapping(index_id).
There is a unit test to validate it.
Also a little patch to work with password strings.
=> feat(lua): New lua method on broker_cache object

.gitignore, bam/src/configuration/applier/bool_expression.cc, bam/src/configuration/applier/kpi.cc, bam/src/configuration/kpi.cc, bam/test/configuration/applier-boolexp.cc, build/bam/CMakeLists.txt, doc/release_notes/broker30.rst
=> fix(bam): While the applier configures the ba, there was a segfault

core/inc/com/centreon/broker/misc/shared_ptr.hh, doc/exploit/stream_connectors.rst, doc/release_notes/broker30.rst, lua/inc/com/centreon/broker/lua/connector.hh, lua/inc/com/centreon/broker/lua/factory.hh, lua/src/broker_socket.cc, lua/src/connector.cc, lua/src/factory.cc, lua/src/main.cc, lua/test/lua.cc
Using the broker_socket, we realized the need of a method to check the connection.
This method is get_state().
=> Lua new function

bam/src/meta_service.cc, storage/src/parser.cc, storage/src/perfdata.cc, storage/src/stream.cc, storage/test/metric/ctor_default.cc, storage/test/perfdata/ctor_default.cc, tcp/src/stream.cc, test/rrd_file.cc
Tested with:
- c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36) **Centos 7**
- c++ (Alpine 6.4.0) 6.4.0
- Alpine clang version 5.0.1 (tags/RELEASE_501/final) (based on LLVM 5.0.1)
- c++8 (FreeBSD Ports Collection) 8.2.0 **GNU GCC**
- FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
=> Changes to newer compilers

sql/mysql_v2/logs.sql, sql/mysql_v3/log_logs.sql, sql/oracle_v2/logs.sql, sql/oracle_v3/log_logs.sql, sql/postgresql_v2/logs.sql, sql/postgresql_v3/log_logs.sql
=> Remove /log_id/ field from SQL tables creation scripts

lua/src/broker_utils.cc, lua/test/lua.cc
=> fix(lua): json_encode/json_decode functions did not escape '\'.

lua/inc/com/centreon/broker/lua/macro_cache.hh, lua/src/luabinding.cc, lua/src/macro_cache.cc, lua/test/lua.cc
=> fix(lua): Cache was lost each time broker restarts.

neb/inc/com/centreon/engine/broker/handle.hh, neb/inc/com/centreon/engine/configuration/applier/state.hh, neb/inc/com/centreon/engine/configuration/host.hh, neb/inc/com/centreon/engine/configuration/service.hh, neb/inc/com/centreon/engine/configuration/state.hh, neb/inc/com/centreon/engine/downtime_finder.hh, neb/inc/com/centreon/engine/objects/host.hh, neb/inc/com/centreon/engine/objects/service.hh, neb/inc/com/centreon/engine/retention/host.hh, neb/inc/com/centreon/engine/retention/service.hh, neb/inc/com/centreon/engine/timeperiod.hh
This patch comes with one of the same name in engine.
The goal is to fix problems in engine reload.
=> Mon 3623 reload engine

neb/inc/com/centreon/engine/contact.hh, neb/inc/com/centreon/engine/customvariable.hh, neb/inc/com/centreon/engine/host.hh, neb/inc/com/centreon/engine/notifier.hh, neb/inc/com/centreon/engine/service.hh
This branch is synchronized with centreon-engine same branch
=> Uninitialized parameters

neb/inc/com/centreon/engine/comment.hh, neb/inc/com/centreon/engine/configuration/applier/state.hh, neb/inc/com/centreon/engine/configuration/hostescalation.hh, neb/inc/com/centreon/engine/configuration/serviceescalation.hh, neb/inc/com/centreon/engine/contact.hh, neb/inc/com/centreon/engine/escalation.hh, neb/inc/com/centreon/engine/hostescalation.hh, neb/inc/com/centreon/engine/notifier.hh, neb/inc/com/centreon/engine/serviceescalation.hh, neb/inc/com/centreon/engine/shared.hh, neb/inc/com/centreon/engine/statusdata.hh
update headers to reflect engine modifications
=> enh(neb): update headers

core/src/config/parser.cc, core/test/config/parser.cc
broker_name was filled we poller_name and poller_name was never set...
=> fix(conf): add unit test for global fields. do not overwrite broker_name

core/src/config/parser.cc, lua/src/broker_cache.cc, lua/src/macro_cache.cc, neb/src/downtime_map.cc
fix(json): std:stol can throw an exception, here we must only use it o…
=> fix(json): std:stol can throw an exception

CMakeLists.txt, core/test/test_server.cc, core/test/test_server.hh, lua/src/broker_socket.cc, lua/test/lua.cc, lua/test/socket.lua
add unit test for broker_tcp_socket
=> enh(lua): add unit test for broker_tcp_socket.

CMakeLists.txt, core/inc/com/centreon/broker/file/stl_fs_browser.hh, core/inc/com/centreon/broker/misc/filesystem.hh, core/inc/com/centreon/broker/misc/misc.hh, core/inc/com/centreon/broker/misc/shared_mutex.hh, core/inc/com/centreon/broker/misc/string.hh, core/inc/com/centreon/broker/modules/loader.hh, core/inc/com/centreon/broker/processing/failover.hh, core/inc/com/centreon/broker/processing/feeder.hh, core/src/config/parser.cc, core/src/file/stl_fs_browser.cc, core/src/misc/diagnostic.cc, core/src/misc/filesystem.cc, core/src/misc/misc.cc, core/src/misc/string.cc, core/src/modules/loader.cc, core/src/processing/acceptor.cc, core/src/processing/failover.cc, core/src/processing/feeder.cc, core/src/processing/thread.cc, core/test/misc/exec.cc, core/test/misc/string.cc, stats/src/parser.cc, test/CMakeLists.txt
fix(config): fix an std:stoi error
enh(loader): remove qt code.
=> enh(diagnostic): remove qt

generator/inc/com/centreon/broker/generator/receiver.hh, generator/src/endpoint.cc, generator/src/receiver.cc, generator/src/sender.cc
=> fix(generator): fix compile

core/test/logging.cc, core/test/modules/module.cc, core/test/multiplexing/engine/hook.cc, core/test/multiplexing/engine/start_stop.cc, core/test/multiplexing/engine/unhook.cc, core/test/multiplexing/publisher/read.cc, core/test/multiplexing/publisher/write.cc, stats/test/stats.cc, storage/test/perfdata.cc
=> enh(test): fix some init deinit dance.

CMakeLists.txt, cmake/tool.cmake, test/CMakeLists.txt
cleanup of cmake files.
add a function to add broker modules.
rework unconnected mode.
=> enh(cmake): first cleanup of cmake files

core/inc/com/centreon/broker/database_config.hh, core/src/database_config.cc, storage/CMakeLists.txt, storage/inc/com/centreon/broker/storage/connector.hh, storage/src/connector.cc, storage/test/connector.cc, storage/test/perfdata.cc, storage/test/rebuild.cc, storage/test/remove_graph.cc
=> enh(storage): more tests

bam/CMakeLists.txt, core/test/test_server.cc, tcp/CMakeLists.txt, tcp/inc/com/centreon/broker/tcp/acceptor.hh, tcp/inc/com/centreon/broker/tcp/connector.hh, tcp/inc/com/centreon/broker/tcp/factory.hh, tcp/inc/com/centreon/broker/tcp/stream.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/factory.cc, tcp/src/main.cc, tcp/src/stream.cc, tcp/test/acceptor.cc, tcp/test/connector.cc, tcp/test/factory.cc, test/CMakeLists.txt
Fix connector to work well with timers.
Add test for acceptor, connector, stream and factory.
Update licence
Fix some bugs.
=> enh(tcp): lots of improvments in tcp module

stats/src/builder.cc, stats/test/stats.cc
fix some lost info on endpoints.
=> enh(stats): fix some lost info on endpoints.

core/src/config/parser.cc, neb/src/neb.cc, stats/test/stats.cc, test/CMakeLists.txt
enh(stats): fix a unit test.
enh(test): only build sql tests on-demand
enh(neb): remove dead code.
=> enh(core): minor parser fixes.

tcp/src/stream.cc, tcp/test/acceptor.cc, tcp/test/connector.cc
enh(tcp): use sync asio.
enh(tcp): fix all unit tests.
=> fix(tcp): fix read.

stats/test/stats.cc
last commit broke stats ut. This commit just fix the ut.
=> enh(stats): fix unit tests.

storage/inc/com/centreon/broker/storage/stream.hh, storage/src/stream.cc
A fix in the insertion query into index_data to be compatible with strict mode.
=> fix(storage): Insert query in index_data not compatible with strict mode

sql/inc/com/centreon/broker/sql/conflict_manager.hh, sql/src/conflict_manager.cc, sql/src/conflict_manager_storage.cc, storage/inc/com/centreon/broker/storage/metric.hh, storage/inc/com/centreon/broker/storage/remove_graph.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/connector.cc, storage/src/metric.cc, storage/src/remove_graph.cc, storage/src/stream.cc, storage/test/metric.cc, storage/test/remove_graph.cc
Regeneration of perfdatas... :-D
=> fix(sql): metrics are generated.

CMakeLists.txt, bam/src/event_cache_visitor.cc, core/inc/com/centreon/broker/config/applier/logger.hh, core/inc/com/centreon/broker/logging/backend.hh, core/inc/com/centreon/broker/logging/manager.hh, core/inc/com/centreon/broker/time/timeperiod.hh, core/src/config/applier/init.cc, core/src/config/applier/logger.cc, core/src/logging/backend.cc, core/src/logging/logger.cc, core/src/logging/manager.cc, core/src/time/timeperiod.cc, core/test/file/splitter/concurrent.cc, core/test/file/splitter/default.cc, core/test/file/splitter/more_than_max_size.cc, core/test/file/splitter/permission_denied.cc, core/test/file/splitter/resume.cc, core/test/file/splitter/split.cc, core/test/logging.cc, core/test/main.cc, influxdb/test/influxdb12.cc, influxdb/test/stream.cc, neb/CMakeLists.txt, neb/src/neb.cc, stats/test/stats.cc, tcp/test/acceptor.cc, tcp/test/connector.cc, watchdog/CMakeLists.txt, watchdog/src/main.cc
Two fixes here:
* The logger had a deadlock we can have if broker cannot load its modules.
* Broker did not compiled with clang++ (bad cmake configuration).
=> Fix logger

graphite/CMakeLists.txt, graphite/inc/com/centreon/broker/graphite/connector.hh, graphite/inc/com/centreon/broker/graphite/factory.hh, graphite/inc/com/centreon/broker/graphite/query.hh, graphite/inc/com/centreon/broker/graphite/stream.hh, graphite/src/connector.cc, graphite/src/factory.cc, graphite/src/query.cc, graphite/src/stream.cc, graphite/test/factory.cc, graphite/test/query.cc, graphite/test/stream.cc, test/CMakeLists.txt
- Add a good test coverage.
- Speedup metric/status resolution.
- escape status service name.
- fix some scheme compilation
- remove some unused code.
=> enh(graphite): lots of minor fixes

graphite/test/query.cc, influxdb/inc/com/centreon/broker/influxdb/line_protocol_query.hh, influxdb/src/line_protocol_query.cc, influxdb/test/line_protocol_query.cc, sql/CMakeLists.txt
- Add better test coverage
- Remove some useless funcs
- Speedup line_protocol_queries for metrics, removing useless caches
- compile conflict_manager tests only with WITH_SQL_TESTS
=> enh(influxdb): lot of small fixes

doc/release_notes/broker19.10.rst, doc/release_notes/index.rst
=> enh(doc): add 19.10 release notes

bam/src/monitoring_stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager_storage.cc
A patch on index_data updates.
=> enh(storage): index_data update fix

rrd/test/exceptions.cc, storage/CMakeLists.txt, tcp/src/acceptor.cc, tcp/test/acceptor.cc
Few more little fixes to have a better coverage.
=> enh(tests): add a better test coverage.

core/test/file/splitter/permission_denied.cc, stats/test/stats.cc, tcp/inc/com/centreon/broker/tcp/acceptor.hh, tcp/inc/com/centreon/broker/tcp/stream.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/stream.cc, tcp/test/acceptor.cc
cleanup socket pointer and fix a test;  2 is a valid port for root.
=> enh(tcp): cleanup socket pointer

README.md, doc/installation/index.rst
Doc updated so that the user knows how to compile broker.
=> enh(doc): README.md needs some changes.

rrd/CMakeLists.txt, rrd/inc/com/centreon/broker/rrd/backend.hh, rrd/inc/com/centreon/broker/rrd/cached.hh, rrd/inc/com/centreon/broker/rrd/connector.hh, rrd/inc/com/centreon/broker/rrd/factory.hh, rrd/src/backend.cc, rrd/src/cached.cc, rrd/src/connector.cc, rrd/src/creator.cc, rrd/src/factory.cc, rrd/src/output.cc, rrd/test/cached.cc, rrd/test/exceptions.cc, rrd/test/factory.cc, rrd/test/lib.cc, rrd/test/rrd.cc
Add a casi full coverage for ut.
=> enh(rrd): add a casi full coverage for ut.

bam/inc/com/centreon/broker/bam/ba.hh, bam/inc/com/centreon/broker/bam/configuration/ba.hh, bam/inc/com/centreon/broker/bam/impact_values.hh, bam/mysql_v2/mod_bam.sql, bam/mysql_v3/cfg_bam.sql, bam/oracle_v2/mod_bam.sql, bam/oracle_v3/cfg_bam.sql, bam/postgresql_v2/mod_bam.sql, bam/postgresql_v3/cfg_bam.sql, bam/src/ba.cc, bam/src/configuration/applier/ba.cc, bam/src/configuration/ba.cc, bam/src/configuration/reader.cc, bam/src/configuration/reader_v2.cc, bam/src/impact_values.cc, bam/src/kpi_ba.cc, bam/src/kpi_boolexp.cc, bam/src/kpi_meta.cc, bam/src/kpi_service.cc, bam/test/ba/kpi_change_at_recompute.cc
Add worst and best status calculation for a ba.
=> bam: add worst and best status calculation for a ba.

bam/inc/com/centreon/broker/bam/ba.hh, bam/inc/com/centreon/broker/bam/bool_expression.hh, bam/inc/com/centreon/broker/bam/configuration/ba.hh, bam/inc/com/centreon/broker/bam/configuration/kpi.hh, bam/inc/com/centreon/broker/bam/impact_values.hh, bam/inc/com/centreon/broker/bam/kpi.hh, bam/inc/com/centreon/broker/bam/kpi_ba.hh, bam/inc/com/centreon/broker/bam/kpi_boolexp.hh, bam/inc/com/centreon/broker/bam/kpi_event.hh, bam/inc/com/centreon/broker/bam/kpi_meta.hh, bam/inc/com/centreon/broker/bam/kpi_service.hh, bam/inc/com/centreon/broker/bam/meta_service.hh, bam/src/ba.cc, bam/src/bool_expression.cc, bam/src/configuration/applier/kpi.cc, bam/src/impact_values.cc, bam/src/kpi.cc, bam/src/kpi_ba.cc, bam/src/kpi_boolexp.cc, bam/src/kpi_event.cc, bam/src/kpi_meta.cc, bam/src/kpi_service.cc, bam/src/meta_service.cc, bam/test/ba/kpi_change_at_recompute.cc
Add ration mechanism for ba status calculation.
=> feat(bam): add ratio mechanism, use an enum for status.

bam/test/ba/kpi_change_at_recompute.cc, doc/exploit/stream_connectors.rst, lua/src/broker_utils.cc, lua/test/lua.cc
New function in the streamconnector to url encode any string.
=> enh(lua): New function broker.url_encode

bam/test/ba/kpi_change_at_recompute.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager_storage.cc
=> fix(storage): update index_data on failed insert

bam/src/ba.cc, core/inc/com/centreon/broker/misc/math.hh, core/inc/com/centreon/broker/multiplexing/muxer.hh, core/src/multiplexing/muxer.cc, core/test/misc/math.cc, doc/release_notes/broker20.04.rst, graphite/inc/com/centreon/broker/graphite/factory.hh, influxdb/src/influxdb12.cc, lua/inc/com/centreon/broker/lua/luabinding.hh, lua/inc/com/centreon/broker/lua/stream.hh, lua/src/luabinding.cc, lua/src/macro_cache.cc, lua/src/stream.cc, test/CMakeLists.txt
Le stream connector is asynchronous now. If a script is too long to execute, messages are sent by broker but it should not slow down it.
=> Mon 3616 async

lua/src/stream.cc
the revamp of lua engine broke the build on debian10
=> fix(lua): fix build on debian arm.

storage/src/conflict_manager_sql.cc
enh(sql): display_name can be absent. use hostname and service_description instead.
=> enh(sql): display_name can be absent. use hostname and

storage/src/conflict_manager_sql.cc
prefer alias and hostname to hostname and service description
=> fix(bam): prefer alias and hostname to hostname and service description.

neb/inc/com/centreon/delayed_delete.hh, neb/inc/com/centreon/handle.hh, neb/inc/com/centreon/handle_action.hh, neb/inc/com/centreon/handle_listener.hh, neb/inc/com/centreon/task.hh
This PR is just a synchronization PR.
Files have been changed in centreon-clib and they need to be updated here to match the clib ones.
=> fix(neb): clib headers need an update

tcp/CMakeLists.txt, tcp/inc/com/centreon/broker/tcp/acceptor.hh, tcp/inc/com/centreon/broker/tcp/connector.hh, tcp/inc/com/centreon/broker/tcp/factory.hh, tcp/inc/com/centreon/broker/tcp/stream.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/test/acceptor.cc, tcp/test/connector.cc, tcp/test/factory.cc
architecture for asio code. This change will :
- increase perfs
- allow us to detect connection lost on adaptor and connector.
**Fixes** #4628
Simon will test it
=> enh(tcp): Move to a totaly asynchronous read

watchdog/src/instance.cc
The watchdog did not wait for the process to be stopped.
=> fix(watchdog): Watchdog waiting with bad condition fixed.

bam/test/time/check_timeperiod.cc, core/inc/com/centreon/broker/config/applier/endpoint.hh, core/inc/com/centreon/broker/config/applier/logger.hh, core/inc/com/centreon/broker/config/applier/modules.hh, core/inc/com/centreon/broker/config/applier/state.hh, core/inc/com/centreon/broker/io/events.hh, core/inc/com/centreon/broker/io/protocols.hh, core/inc/com/centreon/broker/multiplexing/engine.hh, core/inc/com/centreon/broker/time/timezone_manager.hh, core/src/config/applier/endpoint.cc, core/src/config/applier/init.cc, core/src/config/applier/logger.cc, core/src/config/applier/modules.cc, core/src/config/applier/state.cc, core/src/io/events.cc, core/src/io/protocols.cc, core/src/multiplexing/engine.cc, core/src/time/timezone_manager.cc, core/test/main.cc, neb/inc/com/centreon/engine/version.hh, neb/test/randomize.cc, stats/test/stats.cc
This reverts commit 2ff7f10b309fdcf3ad54a8f4f50f21875fc80f0d.
=> Revert "enh(all): Singleton are loaded as adviced by C++11"

script/update-master-ta.pl
New script to execute TA tests.
=> chore(update-master-ta.pl): New script to build TA tests.

core/test/test_server.cc, core/test/test_server.hh, graphite/test/stream.cc, influxdb/test/influxdb12.cc, influxdb/test/stream.cc, lua/test/lua.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/test/acceptor.cc, tcp/test/connector.cc, tcp/test/factory.cc
enh(tcp): cleanup network code.
1/3 of removing network bugs or misconception. This is a general cleanup + a fix of socket cleanup.
=> enh(tcp): remove some polling loop, use condvar instead.

core/test/test_server.cc, core/test/test_server.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/test/connector.cc
Use asynchronous timer instead of polling in tcp::read.
=> Async timer for tcp::read

doc/dev/mapping.rst
Structure description of NebHost packet was wrong. Removed non-existent field from doc.
=> fix(broker/doc): Removed duplicated downtime field

watchdog/src/instance.cc
Just a little bug fix on the watchdog.
=> fix(watchdog): The return value -1 is checked now.

tcp/src/tcp_async.cc
enh(tcp): catch every disconnect and allow us do get the lasts buffer before the disconnection...
=> enh(tcp): catch every disconnect and allow us do get the

core/inc/com/centreon/broker/processing/feeder.hh, core/inc/com/centreon/broker/processing/thread.hh, core/src/processing/acceptor.cc, core/src/processing/feeder.cc, core/src/processing/thread.cc, stats/test/stats.cc
Several fixes to improve the new broker. All is not fixed, we are still working on it.
=> fix(processing): Threads not started.

core/inc/com/centreon/broker/config/applier/endpoint.hh, core/inc/com/centreon/broker/config/applier/logger.hh, core/inc/com/centreon/broker/config/applier/modules.hh, core/inc/com/centreon/broker/config/applier/state.hh, core/inc/com/centreon/broker/io/events.hh, core/inc/com/centreon/broker/io/protocols.hh, core/inc/com/centreon/broker/multiplexing/engine.hh, core/src/config/applier/endpoint.cc, core/src/config/applier/init.cc, core/src/config/applier/logger.cc, core/src/config/applier/modules.cc, core/src/config/applier/state.cc, core/src/io/events.cc, core/src/io/protocols.cc, core/src/main.cc, core/src/multiplexing/engine.cc, core/test/main.cc, core/test/processing/feeder.cc, neb/test/randomize.cc, stats/test/stats.cc
get load/unload mechanism back.
**Fixes** problem on broker reload
reload without problem
=> fix(singleton): get load/unload mechanism back.

bam/src/ba.cc, bam/test/ba/kpi_change_at_recompute.cc
a regression was done by last commit on bam downtime.
This commit should unbreak bam TA.
launch TA
=> fix(bam): a regression was done by last commit on bam downtime.

bam/src/ba.cc
2nd attempt to try to fix bam ta...
=> fix(bam): fix ta

CMakeLists.txt, core/inc/com/centreon/broker/io/endpoint.hh, core/src/config/applier/endpoint.cc, core/src/config/applier/init.cc, core/src/config/applier/state.cc, core/src/io/endpoint.cc, core/src/main.cc, core/src/processing/acceptor.cc, core/src/processing/failover.cc, core/src/processing/thread.cc, core/test/processing/thread.cc, lua/src/luabinding.cc, stats/inc/com/centreon/broker/stats/worker.hh, stats/src/main.cc, stats/src/worker.cc, stats/src/worker_pool.cc, stats/test/stats.cc, tcp/src/tcp_async.cc
This PR improves the behaviour during broker switch off. But it does not solve it.
Now, we are in front of several data races to solve :rofl:
=> Broker stop lock

doc/release_notes/broker19.10.rst, neb/inc/com/centreon/engine/common.hh, neb/inc/com/centreon/engine/configuration/state.hh, neb/inc/com/centreon/engine/downtimes/downtime.hh, neb/inc/com/centreon/engine/downtimes/downtime_manager.hh, neb/inc/com/centreon/engine/events/loop.hh, neb/inc/com/centreon/engine/events/timed_event.hh, neb/inc/com/centreon/engine/macros/defines.hh, neb/src/initial.cc
This is a minor update, but needed to work with Engine from the same branch.
=> enh(neb): neb updated to match engine ones.

doc/release_notes/broker20.04.rst, lua/src/broker_utils.cc, lua/test/lua.cc
The broker.json_decode() function was already implemented in the lua binding but there was no test. Now, we have tests.
=> test(lua): New tests for broker.json_decode function

doc/release_notes/broker19.04.rst, doc/release_notes/broker19.10.rst
update release not for 20.04. I forgot to add it in my last commit.
Sorry for the brainfart...
=> enh(doc): add release notes

core/src/main.cc, core/src/mysql_manager.cc, sql/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager.cc
Start a single instance of broker. Then stop it. It will never stop if you don't have this patch.
=> fix(conflict_manager): Connections could be badly closed.

CMakeLists.txt, core/inc/com/centreon/broker/log_v2.hh, core/src/bbdo/input.cc, core/src/bbdo/input_buffer.cc, core/src/bbdo/internal.cc, core/src/bbdo/output.cc, core/src/bbdo/stream.cc, core/src/log_v2.cc, core/src/main.cc, neb/src/neb.cc, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/factory.cc, tcp/src/main.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc, tls/src/acceptor.cc, tls/src/connector.cc, tls/src/internal.cc, tls/src/main.cc, tls/src/params.cc, tls/src/stream.cc
spdlog is a quick, flexible and simple log library. some log will be using spdlog when a /etc/centreon-broker/log-config.json file will be present.
This file follow this schema: 
{
"log_path": "/tmp/",
"console": true,
"loggers" : [
{
"name": "tls",
"level": "debug"
},
{
"name": "tcp",
"level": "info"
},
{
"name": "bbdo",
"level": "trace"
}
]
}
=> import spdlog for developper usage

tcp/src/stream.cc, tls/src/stream.cc
Allow TLS to work again on broker....
**Fixes** #MON-4946
=> fix(tls): fix tls on 20.04

core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/processing/feeder.cc, sql/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/stored_timestamp.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/stored_timestamp.cc, storage/src/stream.cc
=> fix(sql): various fixes concerning sql engine shutting down

core/src/bbdo/acceptor.cc, core/src/bbdo/connector.cc, core/src/bbdo/factory.cc, core/src/bbdo/stream.cc, core/src/processing/failover.cc
In 20.04, we had difficulties with one peer retention. This patch - written with @SylvestreG improved things a lot. It could not be sufficiant. Let's wait and see.
Follow the test suite of engine/broker.
=> fix(bbdo): A first fix for one peer retention.

CMakeLists.txt, README.md, bam/CMakeLists.txt, conanfile.txt, core/src/log_v2.cc, correlation/CMakeLists.txt, graphite/CMakeLists.txt, influxdb/CMakeLists.txt, lua/CMakeLists.txt, neb/CMakeLists.txt, neb/inc/com/centreon/engine/configuration/applier/logging.hh, rrd/CMakeLists.txt, simu/CMakeLists.txt, sql/CMakeLists.txt, stats/CMakeLists.txt, storage/CMakeLists.txt, tcp/CMakeLists.txt, test/CMakeLists.txt, tls/CMakeLists.txt, watchdog/CMakeLists.txt
add support for conan dependency manager.
=> add support for conan dependency manager.

.gitignore, CMakeLists.txt, Jenkinsfile, conanfile.txt, core/inc/com/centreon/broker/broker_impl.hh, core/inc/com/centreon/broker/brokerrpc.hh, core/inc/com/centreon/broker/log_v2.hh, core/src/broker.proto, core/src/broker_impl.cc, core/src/brokerrpc.cc, core/src/log_v2.cc, core/src/main.cc, core/src/persistent_cache.cc, core/test/rpc/brokerrpc.cc, core/test/rpc/client.cc, neb/src/neb.cc, test/CMakeLists.txt
Add grpc support for broker, by now it support only GetVersion and DebugUpdateConf.
unit test should be enough.
=> Add grpc support for broker

core/inc/com/centreon/broker/broker_impl.hh, core/src/broker.proto, core/src/broker_impl.cc, core/test/rpc/client.cc
fix(ta): try to fix ta. It seems grpc+protobuf in different program cannot share same message name...
=> fix(ta): try to fix ta

CMakeLists.txt, core/inc/com/centreon/broker/broker_impl.hh, core/src/broker.proto, core/src/broker_impl.cc, core/test/rpc/client.cc
use a package namespace to avoid pb message collision
TA should not work on failure
=> fix(grpc): use a package namespace to avoid pb message collision

doc/release_notes/broker20.04.rst, influxdb/src/influxdb12.cc, neb/inc/com/centreon/engine/check_result.hh, neb/inc/com/centreon/engine/configuration/state.hh, neb/inc/com/centreon/engine/shared.hh
Same PR about influxdb as the one for the 19.10.x.
=> Mon 4776 influxdb retention

CMakeLists.txt, core/inc/com/centreon/broker/broker_impl.hh, core/inc/com/centreon/broker/config/applier/modules.hh, core/inc/com/centreon/broker/stats/helper.hh, core/src/broker.proto, core/src/broker_impl.cc, core/src/config/applier/modules.cc, core/src/stats/helper.cc, stats/inc/com/centreon/broker/stats/builder.hh, stats/src/builder.cc
Add these differents rpc for broker : 
com.centreon.broker.Broker.DebugConfReload (reload log config for logV2)
com.centreon.broker.Broker.GetEndpointStats
com.centreon.broker.Broker.GetGenericStats
com.centreon.broker.Broker.GetModulesStats
com.centreon.broker.Broker.GetNumEndpoint
com.centreon.broker.Broker.GetNumModules
com.centreon.broker.Broker.GetSqlStats
with grpc_curl
=> Grpc stats

lua/src/stream.cc
A bad bug in the stream connector is fixed here.
It is a dangling link that is fixed. Very difficult to test :smile:
=> fix(lua): potential dangling pointer removed

sql/src/connector.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/connector.hh, storage/inc/com/centreon/broker/storage/index_mapping.hh, storage/inc/com/centreon/broker/storage/metric.hh, storage/inc/com/centreon/broker/storage/parser.hh, storage/inc/com/centreon/broker/storage/perfdata.hh, storage/inc/com/centreon/broker/storage/rebuild.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/inc/com/centreon/broker/storage/remove_graph.hh, storage/inc/com/centreon/broker/storage/status.hh, storage/inc/com/centreon/broker/storage/stored_timestamp.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/connector.cc, storage/src/factory.cc, storage/src/index_mapping.cc, storage/src/metric.cc, storage/src/parser.cc, storage/src/perfdata.cc, storage/src/rebuild.cc, storage/src/rebuilder.cc, storage/src/remove_graph.cc, storage/src/stored_timestamp.cc, storage/src/stream.cc, storage/test/connector.cc
The graph rebuild has been disabled. This patch fixes this regression.
Rebuild some graphs and see if they are correctly rebuilt.
=> fix(storage): rebuild code is almost back. Tests are still needed.

rrd/src/lib.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/perfdata.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_storage.cc, storage/src/perfdata.cc, storage/src/rebuilder.cc
RRD data type was badly propagated when the user asked to change it.
=> Mon 5178 rebuild rrd2

bam/inc/com/centreon/broker/bam/configuration/applier/kpi.hh, bam/src/ba.cc, bam/src/configuration/applier/kpi.cc, bam/src/configuration/state.cc, bam/src/monitoring_stream.cc
When bool expressions contains errors, ba concerned by them are invalidated. But this functionality was buggy. And broker segfaults...
=> Mon 5232 invalid kpi

core/src/file/splitter.cc
fix a permission error for the queue file. A code path was not trying to create the queue file when it does not exist.
=> fix(splitter): fix a permission error for the queue file.

neb/inc/com/centreon/engine/anomalydetection.hh, neb/inc/com/centreon/engine/check_result.hh, neb/inc/com/centreon/engine/checkable.hh, neb/inc/com/centreon/engine/checks/checker.hh, neb/inc/com/centreon/engine/configuration/hostgroup.hh, neb/inc/com/centreon/engine/configuration/object.hh, neb/inc/com/centreon/engine/configuration/state.hh, neb/inc/com/centreon/engine/globals.hh, neb/inc/com/centreon/engine/host.hh, neb/inc/com/centreon/engine/nebmods.hh, neb/inc/com/centreon/engine/notifier.hh, neb/inc/com/centreon/engine/service.hh, neb/inc/com/centreon/engine/utils.hh
=> chore(neb): neb headers updated

storage/test/perfdata.cc
=> fix(test): A little error in test.

tcp/src/tcp_async.cc
remove some annoying log
async_buf::async_read_cb incoming packet size should disappear from logs...
=> tcp: remove some leftovers logs

doc/release_notes/broker20.04.rst, lua/test/lua.cc, storage/src/conflict_manager.cc, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/parser.cc, storage/test/perfdata.cc
* Improvement of the parser
* Coding style reapplied
* std::stringstream replaced by fmt::format which is faster.
Parser less strict.
- [X ] Patch fixing an issue (non-breaking change)
- [X ] 20.04.x (master)
=> fix(parser): The parser is more permissive

CMakeLists.txt, core/src/main.cc, doc/release_notes/broker20.04.rst, influxdb/src/connector.cc, influxdb/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_storage.cc
This patch fixes crashes that could appear in case of bad database configurations or in case of problems with the database.
=> fix(conflict_manager): In case of a bad conf broker could crash

doc/release_notes/broker20.04.rst, tcp/src/stream.cc
Should fix the bad CRC error message
- [X ] 20.04.x (master)
=> fix(tcp): write always all data.. Do not use write some!

doc/exploit/stream_connectors.rst, doc/release_notes/broker20.04.rst, lua/inc/com/centreon/broker/lua/macro_cache.hh, lua/src/broker_cache.cc, lua/src/macro_cache.cc, lua/test/lua.cc
New function broker_cache:get_severity(host_id, service_id) implemented.
It returns an integer or nil if it does not exist.
=> enh(lua): new cache function get_severity()

doc/release_notes/broker20.04.rst
=> enh(doc): update release notes

README.md
=> fix(readme) : improve documentation

.gitignore, core/src/io/event_info.cc, core/src/mysql_connection.cc, core/src/query_preparator.cc, simu/docker/README, simu/docker/installBroker.sql, simu/docker/partitioning-logs.xml, storage/CMakeLists.txt, storage/src/conflict_manager_sql.cc, storage/src/table_max_size.py
Patch not finished but functional. Logs have been added to better understand several issues.
=> Mon 5488 cols too large

core/inc/com/centreon/broker/bbdo/stream.hh, core/inc/com/centreon/broker/bbdo/version_response.hh, core/src/bbdo/factory.cc, core/src/bbdo/stream.cc, core/src/bbdo/version_response.cc, core/test/bbdo/output.cc, tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/src/tcp_connection.cc, tcp/test/connector.cc
If negotiation is disabled, connection can fail.
=> Mon 6087 negotiation disabled

core/inc/com/centreon/broker/bbdo/stream.hh, core/inc/com/centreon/broker/bbdo/version_response.hh, core/src/bbdo/factory.cc, core/src/bbdo/stream.cc, core/src/bbdo/version_response.cc, core/test/bbdo/output.cc, tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/src/tcp_connection.cc, tcp/test/connector.cc
If negotiation is disabled, connection can fail.
=> Mon 6087 negotiation disabled 20.10

CMakeLists.txt, core/inc/com/centreon/broker/config/applier/state.hh, core/inc/com/centreon/broker/config/state.hh, core/inc/com/centreon/broker/log_v2.hh, core/inc/com/centreon/broker/pool.hh, core/src/config/applier/state.cc, core/src/config/parser.cc, core/src/config/state.cc, core/src/main.cc, core/src/mysql.cc, core/src/pool.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/factory.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc
=> Thread pool

bam/src/availability_thread.cc, core/inc/com/centreon/broker/io/endpoint.hh, core/inc/com/centreon/broker/misc/pair.hh, core/src/bbdo/stream.cc, core/src/processing/failover.cc, tcp/inc/com/centreon/broker/tcp/connector.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/tcp_async.cc
Socket should better closed on incidents
=> Mon 6157 socket closed graciously

script/misc/check_broker_config.py
adding a new script to centreon broker, this script check broker config files
=> enh(script): add check broker config script

.github/PULL_REQUEST_TEMPLATE.md
- Update the PULL_REQUEST_TEMPLATE 
- Remove unsupported versions
- Add new maintenance branch
=> enh(PULL_REQUEST_TEMPLATE): deprecate old versions and update

Jenkinsfile
trigger properly centreon-web job (branch name instead of master)
=> chore(build): trigger properly centreon-web job

tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/tcp_connection.cc, tcp/test/acceptor.cc
TCP streams should be faster when we have rentetion files.
=> Mon 6367 ipv4 bad flush

storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_sql.cc
Logs are sent in bulk to the database, this is really faster.
=> en(sql): logs are sent in bulk

bam/inc/com/centreon/broker/bam/monitoring_stream.hh, bam/src/availability_thread.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, core/inc/com/centreon/broker/database/mysql_error.hh, core/inc/com/centreon/broker/database/mysql_task.hh, core/inc/com/centreon/broker/mysql.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql.cc, core/src/mysql_connection.cc, doc/en/release_notes/broker20.04.rst, sql/src/cleanup.cc, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/rebuilder.cc
BAM availabilities computations may double durations.
=> Mon 6397 bam reporting double duration 20.04

cmake.sh
=> Build debian

core/src/config/applier/state.cc, core/src/config/parser.cc
https://centreon.atlassian.net/browse/MON-5644?atlOrigin=eyJpIjoiZTk5NTRlMWY3NjBjNDBjMTkyYTFkOTIzMWUzYThkYWEiLCJwIjoiaiJ9
=> fix(broker_name) : add Allow point as a valid character for ouput's name

neb/inc/com/centreon/engine/nebstructs.hh, neb/src/callbacks.cc
=> enh(Flapping) change hostname to host_id and service_id

core/inc/com/centreon/broker/config/applier/endpoint.hh, core/inc/com/centreon/broker/config/applier/init.hh, core/inc/com/centreon/broker/log_v2.hh, core/inc/com/centreon/broker/multiplexing/engine.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/mysql_manager.hh, core/inc/com/centreon/broker/processing/failover.hh, core/src/broker_impl.cc, core/src/config/applier/endpoint.cc, core/src/config/applier/init.cc, core/src/log_v2.cc, core/src/main.cc, core/src/multiplexing/engine.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/processing/failover.cc, core/test/config/parser.cc, doc/en/release_notes/broker20.04.rst, lua/src/broker_utils.cc, lua/src/stream.cc, sql/src/connector.cc, sql/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager.cc, storage/src/rebuilder.cc, storage/src/stream.cc
This patch corrects many issues when Broker is badly configured and we want to stop it.
This patch also fixes the storage rebuilder mechanism.
REFS: MON-6369 ; MON-4952
=> Mon 6369 broker hangs alone 20.04

core/inc/com/centreon/broker/config/applier/endpoint.hh, core/inc/com/centreon/broker/config/applier/init.hh, core/inc/com/centreon/broker/log_v2.hh, core/inc/com/centreon/broker/multiplexing/engine.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/mysql_manager.hh, core/inc/com/centreon/broker/processing/failover.hh, core/src/broker_impl.cc, core/src/config/applier/endpoint.cc, core/src/config/applier/init.cc, core/src/log_v2.cc, core/src/main.cc, core/src/multiplexing/engine.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/processing/failover.cc, core/test/config/parser.cc, lua/src/broker_utils.cc, lua/src/stream.cc, sql/src/connector.cc, sql/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager.cc, storage/src/rebuilder.cc, storage/src/stream.cc
This patch corrects many issues when Broker is badly configured and we want to stop it.
This patch also fixes the storage rebuilder mechanism.
REFS: MON-6369 ; MON-4952
=> Mon 6369 broker hangs alone

README.md, cmake.sh, core/test/bbdo/output.cc, neb/inc/com/centreon/clib.hh, neb/inc/com/centreon/clib/version.hh, neb/inc/com/centreon/delayed_delete.hh, neb/inc/com/centreon/engine/engine_impl.hh, neb/inc/com/centreon/engine/enginerpc.hh, neb/inc/com/centreon/exceptions/basic.hh, neb/inc/com/centreon/handle_action.hh, neb/inc/com/centreon/handle_listener.hh, neb/inc/com/centreon/handle_manager.hh, neb/inc/com/centreon/logging/logger.hh, neb/inc/com/centreon/process.hh, neb/inc/com/centreon/process_manager.hh, neb/inc/com/centreon/task_manager.hh, neb/inc/com/centreon/timestamp.hh, neb/inc/com/centreon/unordered_hash.hh
This patch complete the changes in centreon-clib and centreon-engine.
REFS: MON-5939
=> Mon 5939 processes locks

CMakeLists.txt, README.md, cmake.sh, core/test/bbdo/output.cc
=> Mon 6521 study arm compilation

CMakeLists.txt, README.md, cmake.sh, core/test/bbdo/output.cc
=> Mon 6521 study arm compilation 20.10

README.md
=> enh(project): enhance root readme

CHANGELOG.md, CMakeLists.txt, core/src/file/splitter.cc, core/src/main.cc, neb/inc/com/centreon/clib/version.hh.in, neb/inc/com/centreon/engine/commands/command.hh, neb/inc/com/centreon/engine/commands/command_listener.hh, neb/inc/com/centreon/engine/commands/connector.hh, neb/inc/com/centreon/engine/commands/forward.hh, neb/inc/com/centreon/engine/commands/raw.hh, neb/inc/com/centreon/engine/events/loop.hh, neb/inc/com/centreon/engine/host.hh, neb/inc/com/centreon/engine/logging/broker.hh, neb/inc/com/centreon/engine/my_lock.hh, neb/inc/com/centreon/engine/notifier.hh, neb/inc/com/centreon/engine/opt.hh, neb/inc/com/centreon/engine/service.hh, neb/inc/com/centreon/process_listener.hh, neb/inc/com/centreon/process_manager.hh, neb/src/neb.cc, tls/inc/com/centreon/broker/tls/acceptor.hh, tls/inc/com/centreon/broker/tls/connector.hh, tls/inc/com/centreon/broker/tls/factory.hh, tls/inc/com/centreon/broker/tls/params.hh, tls/src/acceptor.cc, tls/src/connector.cc, tls/src/factory.cc, tls/src/params.cc
=> fix(tls):TLS common name check impossible if it is too long

Jenkinsfile, simu/docker/bam.sql, sonar-project.properties
Transition from sonarQube community to dev edition 
**Fixes** # (MON-5609)
**Requires: https://github.com/centreon/centreon-build/pull/473**
=> enh(chore): integrate sonarQube dev edition

core/inc/com/centreon/broker/config/state.hh, core/inc/com/centreon/broker/mapping/entry.hh, core/src/config/state.cc, core/src/mapping/entry.cc
=> fix(log_v2): If conf contains no "log" conf, the directory was badly initialized.

core/inc/com/centreon/broker/mapping/entry.hh, core/inc/com/centreon/broker/mapping/property.hh, core/inc/com/centreon/broker/mapping/source.hh, core/inc/com/centreon/broker/misc/pair.hh, core/src/bbdo/stream.cc, core/src/mapping/entry.cc, lua/src/broker_event.cc, lua/src/broker_utils.cc, storage/CMakeLists.txt, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/index_mapping.hh, storage/inc/com/centreon/broker/storage/metric_mapping.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/inc/com/centreon/broker/storage/remove_graph.hh, storage/inc/com/centreon/broker/storage/status.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_storage.cc, storage/src/index_mapping.cc, storage/src/metric_mapping.cc, storage/src/rebuilder.cc, storage/src/remove_graph.cc, storage/src/status.cc, storage/test/status-entry.cc
=> Mon 6801 index data

CHANGELOG.md, core/inc/com/centreon/broker/mapping/entry.hh, core/inc/com/centreon/broker/mapping/property.hh, core/inc/com/centreon/broker/mapping/source.hh, core/inc/com/centreon/broker/misc/pair.hh, core/src/bbdo/stream.cc, core/src/mapping/entry.cc, lua/src/broker_event.cc, lua/src/broker_utils.cc, storage/CMakeLists.txt, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/index_mapping.hh, storage/inc/com/centreon/broker/storage/metric_mapping.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/inc/com/centreon/broker/storage/remove_graph.hh, storage/inc/com/centreon/broker/storage/status.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_storage.cc, storage/src/index_mapping.cc, storage/src/metric_mapping.cc, storage/src/rebuilder.cc, storage/src/remove_graph.cc, storage/src/status.cc, storage/test/status-entry.cc
* fix(conflict_manager_storage): replace index_data in uint64
* enh(status.hh): change type for index_data
* enh(storage:status): index_is is uint64 now.
* enh(bbdo/stream): add ulong in serialize and unserialize + unit test is ok
* enh(conflict_manager): replace index_id in uint64
* enh(conflict_manager): fix troncated index_id in metrics table
* enh(storage): fix syntax
REFS: MON-6801
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear …
=> fix(bbdo): replace index_id with uint64 type

tls/src/params.cc
=> fix(tls) Remove SSL protocol and deprecated cipher-suites

core/inc/com/centreon/broker/config/endpoint.hh, core/src/config/parser.cc
throw message when retry-interval is wrong
=> enh(core/config): throw message when retry-interval is wrong

core/src/mysql_connection.cc, storage/src/conflict_manager_storage.cc
=> fix (storage): delete log sql on duplicate entry

CHANGELOG.md, bam/CMakeLists.txt, bam/inc/com/centreon/broker/bam/kpi_ba.hh, bam/src/ba.cc, bam/src/configuration/applier/kpi.cc, bam/src/kpi_ba.cc, bam/test/ba/kpi_ba.cc, bam/test/test-visitor.hh, test/CMakeLists.txt
Unknown states taken in count for ba impacts.
REFS: MON-7149
=> Mon 7149 unknown status vs impact 20.10

core/inc/com/centreon/broker/misc/string.hh, core/src/misc/string.cc, core/src/time/timerange.cc, core/test/time/timerange.cc, test/CMakeLists.txt
=> Mon 7176 20.10.x

CHANGELOG.md, CMakeLists.txt, bam/CMakeLists.txt, cmake.sh, conanfile.txt, correlation/CMakeLists.txt, graphite/CMakeLists.txt, influxdb/CMakeLists.txt, lua/CMakeLists.txt, neb/CMakeLists.txt, rrd/CMakeLists.txt, simu/CMakeLists.txt, sql/CMakeLists.txt, stats/CMakeLists.txt, storage/CMakeLists.txt, tcp/CMakeLists.txt, test/CMakeLists.txt, tls/CMakeLists.txt, watchdog/CMakeLists.txt
cbd builds with conan-center.
On centos7 devtoolset-9 needs to be installed.
=> Using conan center 20.04

CHANGELOG.md, core/inc/com/centreon/broker/misc/string.hh, core/src/misc/string.cc, core/src/time/timerange.cc, core/test/time/timerange.cc, test/CMakeLists.txt
=> Mon 7176 21.04.x

core/src/bbdo/stream.cc
Move BBDO serialized and unserialized events logs from debug to trace
=> Mon 7238 log conversion

CHANGELOG.md, core/src/bbdo/stream.cc
Move BBDO serialized events logs from debug to trace.
=> Mon 7238 20.04.x

CHANGELOG.md, core/src/bbdo/stream.cc, storage/test/status-entry.cc
=> fix(bbdo): fix Index_id of metrics tables are now in unsigned int64_t.

CMakeLists.txt, README.md, core/test/logging.cc
=> Mon 7395 compilation arm

CHANGELOG.md, CMakeLists.txt, README.md, cmake.sh, core/test/logging.cc
=> Mon 7395 compilation arm 21.04

CHANGELOG.md, CMakeLists.txt, README.md, cmake.sh, core/test/logging.cc
=> Mon 7395 compilation arm 20.10

CHANGELOG.md, CMakeLists.txt, README.md, cmake.sh, core/test/logging.cc
=> Mon 7395 compilation arm 20.04

core/src/config/parser.cc, core/test/config/parser.cc
add unit test for loggers field located configuration file with 
=> enh(core/parser): unit test and log in parser

CHANGELOG.md, CMakeLists.txt, core/inc/com/centreon/broker/bbdo/factory.hh, core/inc/com/centreon/broker/brokerrpc.hh, core/inc/com/centreon/broker/processing/acceptor.hh, core/inc/com/centreon/broker/processing/feeder.hh, core/src/brokerrpc.cc, core/src/processing/acceptor.cc, core/src/processing/feeder.cc, core/test/compression/stream/memory_stream.hh, core/test/config/parser.cc, core/test/multiplexing/engine/hooker.hh, core/test/processing/temporary_stream.hh, core/test/rpc/brokerrpc.cc, core/test/test_server.cc, lua/src/broker_log.cc, storage/test/perfdata.cc, tcp/inc/com/centreon/broker/tcp/stream.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/test/acceptor.cc
Connection/Deconnection rewritten.
REFS: MON-7373
=> Mon 7373 reconnection reviewed 20.10

CMakeLists.txt, core/inc/com/centreon/broker/processing/acceptor.hh, core/inc/com/centreon/broker/processing/feeder.hh, core/src/log_v2.cc, core/src/processing/acceptor.cc, core/src/processing/feeder.cc, core/test/test_server.cc, lua/src/broker_log.cc, tcp/inc/com/centreon/broker/tcp/stream.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/main.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/test/acceptor.cc, tcp/test/connector.cc
Several issues on engine/broker connection/deconnection are fixed.
REFS: MON-7373
=> Mon 7373 reconnection reviewed

CMakeLists.txt, core/inc/com/centreon/broker/bbdo/factory.hh, core/inc/com/centreon/broker/brokerrpc.hh, core/inc/com/centreon/broker/processing/acceptor.hh, core/inc/com/centreon/broker/processing/feeder.hh, core/src/brokerrpc.cc, core/src/log_v2.cc, core/src/processing/acceptor.cc, core/src/processing/feeder.cc, core/test/compression/stream/memory_stream.hh, core/test/multiplexing/engine/hooker.hh, core/test/processing/temporary_stream.hh, core/test/rpc/brokerrpc.cc, core/test/test_server.cc, influxdb/src/line_protocol_query.cc, lua/src/broker_log.cc, tcp/inc/com/centreon/broker/tcp/stream.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/main.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/test/acceptor.cc, tcp/test/connector.cc
Engine/Broker Connection/Deconnection rewritten.
Several issues should be fixed around connections issues.
REFS: MON-7373
=> Mon 7373 reconnection reviewed master

core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc, core/src/mysql_manager.cc, stats/test/stats.cc
This is useful to give an operational connection and not one already
disconnected.
REFS: MON-6917
=> fix(mysql): New method mysql_connection::ping()

CHANGELOG.md, core/inc/com/centreon/broker/database_config.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/database_config.cc, core/src/mysql_connection.cc, core/test/config/parser.cc, sql/inc/com/centreon/broker/sql/cleanup.hh, sql/src/cleanup.cc, storage/test/connector.cc
=> Mon 7312 my sql unix socket 21.04

core/inc/com/centreon/broker/database_config.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/database_config.cc, core/src/mysql_connection.cc, core/test/config/parser.cc, sql/inc/com/centreon/broker/sql/cleanup.hh, sql/src/cleanup.cc, storage/test/connector.cc
=> fix(sql): Add a parameter to select the MySQL UNIX socket

CHANGELOG.md, bam/inc/com/centreon/broker/bam/ba_duration_event.hh, bam/inc/com/centreon/broker/bam/kpi_event.hh, bam/src/ba.cc, bam/src/ba_duration_event.cc, bam/src/configuration/applier/ba.cc, bam/src/configuration/kpi.cc, bam/src/configuration/reader_v2.cc, bam/src/kpi.cc, bam/src/kpi_ba.cc, bam/src/kpi_boolexp.cc, bam/src/kpi_event.cc, bam/src/kpi_service.cc, bam/src/main.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, bam/src/service_book.cc, bam/test/ba/kpi_ba.cc, bam/test/ba/kpi_service.cc, bam/test/exp_builder/availability_builder.cc, cmake.sh, core/inc/com/centreon/broker/bbdo/version_response.hh, core/inc/com/centreon/broker/io/extension.hh, notification/src/stream.cc, sql/src/stream.cc, storage/src/conflict_manager_sql.cc, tcp/src/tcp_async.cc
A new BA with new KPI has its start time values not correctly initialized. This patch fixes this point.
REFS: MON-7405
=> Mon 7405 new ba start time not initialized 21.04

bam/src/availability_thread.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, core/inc/com/centreon/broker/database/mysql_task.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/processing/failover.hh, core/src/config/applier/endpoint.cc, core/src/main.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/pool.cc, core/src/processing/acceptor.cc, core/src/processing/failover.cc, core/src/processing/feeder.cc, lua/src/stream.cc, sql/src/cleanup.cc, stats/src/worker.cc, storage/src/conflict_manager.cc, storage/src/stream.cc
A possible deadlock in cbd when it is stopped, has been removed.
REFS: MON-10681
=> fix(mysql_connection): possible deadlock removed when cbd is stopped.

CHANGELOG.md, bam/src/availability_thread.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, core/inc/com/centreon/broker/database/mysql_task.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/processing/failover.hh, core/src/config/applier/endpoint.cc, core/src/main.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/pool.cc, core/src/processing/acceptor.cc, core/src/processing/failover.cc, core/src/processing/feeder.cc, lua/src/stream.cc, sql/src/cleanup.cc, stats/src/worker.cc, storage/src/conflict_manager.cc, storage/src/stream.cc
A possible deadlock in cbd when it is stopped, has been removed.
REFS: MON-10681
=> Mon 10681 cbd deadlock 21.04

CHANGELOG.md, bam/src/availability_thread.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, core/inc/com/centreon/broker/database/mysql_task.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/processing/acceptor.hh, core/inc/com/centreon/broker/processing/endpoint.hh, core/inc/com/centreon/broker/processing/failover.hh, core/inc/com/centreon/broker/processing/feeder.hh, core/inc/com/centreon/broker/processing/stat_visitable.hh, core/src/config/applier/endpoint.cc, core/src/main.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/pool.cc, core/src/processing/acceptor.cc, core/src/processing/failover.cc, core/src/processing/feeder.cc, lua/src/stream.cc, neb/src/downtime_scheduler.cc, sql/src/cleanup.cc, sql/src/stream.cc, stats/src/worker.cc, storage/src/conflict_manager.cc, storage/src/stream.cc
A possible deadlock in cbd when it is stopped, has been removed.
REFS: MON-10681
=> Mon 10681 cbd deadlock 20.10

Jenkinsfile
=> fix(ci): manage sonar quality gate timeout

Jenkinsfile
Adjusting quality gate sleeping for C++ sonar "analysis"
=> fix(ci): adjust sleeping limit

core/inc/com/centreon/broker/broker_impl.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/mysql_manager.hh, core/inc/com/centreon/broker/stats/center.hh, core/src/broker.proto, core/src/broker_impl.cc, core/src/mysql_connection.cc, core/src/stats/center.cc, core/test/rpc/brokerrpc.cc, core/test/rpc/client.cc
=> MON-6242-sql-connections

.gitignore, cmake.sh, influxdb/inc/com/centreon/broker/influxdb/line_protocol_query.hh, influxdb/src/line_protocol_query.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager.cc, storage/src/parser.cc, storage/src/rebuilder.cc, storage/test/perfdata.cc
index_id is an uint64.
REFS: MON-10966
=> Mon 10966 index id 32 64

.gitignore, CHANGELOG.md, Jenkinsfile, cmake.sh, influxdb/inc/com/centreon/broker/influxdb/line_protocol_query.hh, influxdb/src/line_protocol_query.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager.cc, storage/src/parser.cc, storage/src/rebuilder.cc, storage/test/perfdata.cc
index_id is uint64.
REFS: MON-10966
=> Mon 10966 index id 32 64 20.10

.gitignore, CHANGELOG.md, cmake.sh, influxdb/inc/com/centreon/broker/influxdb/line_protocol_query.hh, influxdb/src/line_protocol_query.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/src/conflict_manager.cc, storage/src/parser.cc, storage/src/rebuilder.cc, storage/test/perfdata.cc
index_id is an uint64.
REFS: MON-10966
=> Mon 10966 index id 32 64 21.04

cmake.sh
Add support to use `cmake.sh` with Ubuntu.
Tested with Ubuntu 20.04 (LTS) and 21.04
=> add support to use with Ubuntu

storage/src/conflict_manager_storage.cc
=> fix(rrd): add a loop to delete metric file

CHANGELOG.md, storage/src/conflict_manager_storage.cc
=> Mon 6155 rrd file not deleted 21.04

Jenkinsfile
fix qaBranch variable to allow delivery on dev-* branches
- [] 20.04.x
=> fix(ci): fixing qaBranch variable

storage/src/conflict_manager_storage.cc
=> fix(rrd): add a loop to delete metric file (#655)

CHANGELOG.md, bam/src/ba.cc, storage/src/conflict_manager_storage.cc
=> fix(rrd): add query sql to check metrics to delete

core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc
Here is the good fix for mysql_ping issue.
REFS: MON-11530
=> Mon 11530 mysql ping 20.10

core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc, rrd/test/cached.cc, stats/inc/com/centreon/broker/stats/worker_pool.hh, tcp/src/tcp_connection.cc
This time mysql_ping should be better.
REFS: MON-11530
=> fix(mysql_connection): mysql_ping is far less aggressive.

SECURITY.md
=> enh(secu): update GPG key

CHANGELOG.md, bam/src/configuration/reader_v2.cc, core/src/mysql_connection.cc
Regression in bam on services cache fixed.
REFS: MON-12070
=> Mon 12070 bam services cache too selective 21.04
