centreon/centreon-broker

influxdb/src/influxdb10.cc
Since influxdb 1.0 the timestamp uses a int64 https://docs.influxdata.com/influxdb/v1.0/write_protocols/line_protocol_tutorial/#timestamp
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#data-types
Status code 204 => OK => https://docs.influxdata.com/influxdb/v1.2/tools/api/#status-codes-and-responses-2
Double quote string field values, Never for measurements, tag keys, tag values, field keys => https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#quoting
Build OK : 
[root@localhost build]# make
[ 27%] Built target rokerbase
[ 27%] Built target roker
[ 27%] Built target cbd
[ 29%] Built target cbwd
[ 31%] Built target 15-stats
[ 38%] Built target nebbase
[ 41%] Built target 10-neb
[ 51%] Built target cbmod
[ 63%] Built target …
=> influxdb: fix for influxdb 1.x

storage/src/rebuilder.cc
There is a mismatch in the passed paramters to _rebuild_metric() that causes metrics to not be properly rebuilt, or rebuilt with wrong data!
See the definition of _revuild_metric().
The problem surfaced from this forum post:
https://forum.centreon.com/forum/centreon-collect/centreon-broker/143995-unable-to-rebuild-rrd
Please accept as bugfix; it fixes the issue.
=> Fixes error in rebuilding metrics

doc/release_notes/broker30.rst, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/src/rebuilder.cc
Indexes (host or service) are now processed one by one. This allows
cancellation of massive graph rebuilt after the current index has
been processed.
=> feat(storage): allow cancellation of graph rebuild

doc/release_notes/broker30.rst, storage/src/rebuilder.cc
The /must_be_rebuild/ flag of the /index_data/ table was properly
updated to 2 but within an uncommitted transaction. This prevented
users from getting the current rebuilding status.
=> fix(storage): mark graphs as being rebuild.

build/CMakeLists.txt, build/CodeCoverage.cmake, build/tests/CMakeLists.txt
The cmake option WITH_COVERAGE=On must be provided in complement to
WITH_TESTING=On.
Then, the command _make test-coverage_ executes the tests and fills
a directory 'coverage' containing the coverage.
=> feat(CMakeLists.txt): Code coverage added on unit tests.

graphite/inc/com/centreon/broker/graphite/connector.hh, graphite/inc/com/centreon/broker/graphite/query.hh, graphite/inc/com/centreon/broker/graphite/stream.hh, graphite/src/connector.cc, graphite/src/factory.cc, graphite/src/query.cc, graphite/src/stream.cc
Endpoints with the /graphite/ type now have a /escape_string/
configuration parameter. It is used to replace dots (.) in service
description, host names, metric names, ... to avoid unwanted
hierarchical ordering in Graphite. By default this parameter is
set to underscore (_). That is dots are replaced by underscores.
=> feat(graphite): escape dots.

bam/inc/com/centreon/broker/bam/configuration/applier/kpi.hh, bam/src/configuration/applier/kpi.cc, bam/src/kpi_event.cc
When the kpi configuration applier applies the configuration, the
connection betwwen kpis and targets may be cut. Now, a new step
is done consisting in checking and reestablishing connections.
This patch should fix issue #145
=> fix(bam): Bad boolexp computation

core/inc/com/centreon/broker/file/cfile.hh, core/inc/com/centreon/broker/file/fs_file.hh, core/inc/com/centreon/broker/file/splitter.hh, core/inc/com/centreon/broker/file/stream.hh, core/inc/com/centreon/broker/multiplexing/muxer.hh, core/inc/com/centreon/broker/persistent_file.hh, core/src/file/cfile.cc, core/src/file/splitter.cc, core/src/file/stream.cc, core/src/multiplexing/muxer.cc, core/src/persistent_file.cc, core/src/processing/feeder.cc, core/test/file/splitter/concurrent.cc, core/test/file/test_file.cc, core/test/file/test_file.hh
Instead of keeping them, we delete them. This is done from subscriber class
because we have the same behavior for all subscribers than for maps.
=> feat(muxer): Old queue files are not used by maps.

build/CMakeLists.txt
This is a little patch to cancel broker compilation if the development liblua library is not installed.
=> fix(lua): Compiling broker with lua without liblua is now impossible

bam/src/dimension_kpi_event.cc, doc/exploit/stream_connectors.rst, lua/inc/com/centreon/broker/lua/macro_cache.hh, lua/src/broker_cache.cc, lua/src/broker_utils.cc, lua/src/macro_cache.cc, lua/test/lua.cc
The goal here is to add methods to the broker cache provided by the Lua module.
New methods are:
get_hostgroup_name(hg_id)
get_hostgroups(host_id)
get_servicegroup_name(sg_id)
get_servicegroups(host_id, service_id)
They are all tested in unit tests.
=> Lua cache improvement

doc/conf.py, doc/installation/index.rst
Add instructions to use the new repository and update instructions to install packages.
Fix depencies to build source.
Tested installation based on documentation.
- Centos 6
- Centos 7
- Debian Jessie
- Debian Stretch
- Ubuntu 14.04
- Ubuntu 16.04
=> update content with new repository CentOS7 and fixes dependency

influxdb/inc/com/centreon/broker/influxdb/macro_cache.hh, influxdb/src/macro_cache.cc
Configure the influxdb output on your centreon. You should configure the output such that hostnames or service descriptions are used in the output.
Restart cbd, you won't have hostnames and service descriptions. To have them again, restart engine.
This patch fixes that. With it, when you restart cbd, the cache is correctly reloaded.
=> fix(influxdb): The cache was badly removed on cbd restart.

graphite/inc/com/centreon/broker/graphite/macro_cache.hh, graphite/src/macro_cache.cc
Add a graphite output to broker. Use hostnames and service descriptions to your outputs.
You have to restart engine to fill the output cache.
The next time you'll restart cbd, this cache will be lost except if you apply this patch.
=> fix(graphite): Cache was lost on cbd restart

storage/src/stream.cc
The `enum` type must be a string format because strict mode of MariaDB.
error output with strict mode enabled:
```
ERROR 1265: Data truncated for column 'status' at row 1 : INSERT INTO data_bin  (id_metric   , ctime, status, value)  VALUES (1, 1558007396, 0, '1.9687900000e+02')
```
=> (fix) fix enum input with strict mode

stats/src/parser.cc, stats/test/stats.cc
The parser was waiting for an json:object {json_fifo: ...}
but sometime it can take an array of json:object like
[{json_fifo: ...}]
=> enh(stats): fix a bug in the parser.

bam/inc/com/centreon/broker/bam/dimension_kpi_event.hh, core/inc/com/centreon/broker/mapping/property.hh, graphite/src/query.cc, influxdb/src/line_protocol_query.cc, storage/inc/com/centreon/broker/storage/metric.hh
Revert support of uint64_t in property.hh, this change needs an update of BBDO.
We are too far away in the release cycle to put this change.
=> enh(bbdo): uint64_t are not supported yet by BBDO.

bam/src/reporting_stream.cc, test/bam/v2/main.cc
Data we insert into those columns are far too long. And we never use them. So the solution is not to continue to insert them.
=> fix(bam): No more need of first_perfdata, first_output

bam/src/monitoring_stream.cc, core/inc/com/centreon/broker/timestamp.hh
Avoid to update downtime.end_time and downtime.duration to bigint columns
Refs: BAM-750
=> enh(sql): reduce max timestamp to match integer value

doc/release_notes/broker20.04.rst, doc/release_notes/index.rst, neb/inc/com/centreon/broker/neb/log_entry.hh, neb/src/callbacks.cc, neb/src/set_log_data.cc, neb/test/set_log_data.cc
Add a log entry for all kind of event_handler.
By now broker will do what it is needed to log event_handler in the centreon-web page :  "Monitoring > Event Logs > Event Logs"
=> enh(log): add a log entry for all kind of event_handler

storage/src/conflict_manager_sql.cc
Services without display_name are fake internal services needed by BAM to construct is tree. So we do not want to store them in database
=> fix(bam): services without display_name are fake

script/systemd/cbd.service.in
Hi,
This closes #199, starting cbd after mariadb.
Similar to https://github.com/centreon/centreon-engine/pull/172.
Thank you :+1: 
Edit : issue still present in centreon-broker 19.10.2.
=> Start cbd after mariadb

watchdog/src/instance.cc, watchdog/src/main.cc
The watchdog waits a longer time before killing the process.
And when it must kill the process, it waits for its dead.
With a centreon broker running. Enter the following command to get the cbd pid running :+1: 
`ps ax | grep cbd`
Open the the /etc/centreon-broker/watchdog.json and change the name of one of the broker instances, for example we can choose successively the following names "central-rrd-master", "central-rrd-master1", "central-rrd-master2", ...
Each time the name is changed, execute as root the command 'systemctl reload cbd'.
When the command is finished, verify that there is always two cbd instances, the one whose name did not change has the same pid and the other has a new pid. To verify this, enter the following command:
`ps …
=> fix(watchdog): if a sigkill is sent, watchdog wait for it now

core/test/test_server.cc, core/test/test_server.hh, neb/test/custom_variable.cc, neb/test/custom_variable_status.cc, neb/test/event_handler.cc, neb/test/flapping_status.cc, neb/test/host.cc, tcp/inc/com/centreon/broker/tcp/acceptor.hh, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/tcp_async.cc, tcp/test/acceptor.cc
Do not thow exception on tcp::acceptor::listen_on. When we try to bind on a unavailable port, broker was exiting without whining....
=> Do not thow exception on tcp::acceptor::listen_on

bam/inc/com/centreon/broker/bam/ba.hh, bam/inc/com/centreon/broker/bam/configuration/ba.hh, bam/src/ba.cc, bam/src/configuration/applier/ba.cc, bam/src/configuration/ba.cc, bam/src/configuration/reader_v2.cc, bam/test/ba/kpi_change_at_recompute.cc
Add support for the new BA Dowtime behaviour. Now a BA can 
- inherit the downtime
- ignore the downtime
- ignore a kpi that is in downtime.
**Fixes** #BAM-834
You need to have the new calculation interface in bam and play with the ba downtime configuration
=> feat(bam): add a new downtime mechanism => ignore_kpi

bam/inc/com/centreon/broker/bam/kpi.hh, bam/inc/com/centreon/broker/bam/kpi_event.hh, bam/inc/com/centreon/broker/bam/reporting_stream.hh, bam/src/configuration/applier/kpi.cc, bam/src/configuration/reader_v2.cc, bam/src/kpi.cc, bam/src/kpi_ba.cc, bam/src/kpi_boolexp.cc, bam/src/kpi_event.cc, bam/src/kpi_meta.cc, bam/src/kpi_service.cc, bam/src/reporting_stream.cc, core/inc/com/centreon/broker/database/mysql_task.hh, core/inc/com/centreon/broker/mysql.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql.cc, core/src/mysql_connection.cc, storage/src/conflict_manager_storage.cc
Steps to reproduce the issue:
Create a BA and check "Automatically inherit KPI downtimes ?"
Set a Downtime on a KPI
Simulate a critical on this KPI (So my BA is in downtime)
Remove the downtime on my KPI (So my BA is not anymore in downtime)
Describe the results you received:
I have no kpi_event_id list for my ba_event_id when my the downtime is removed :
SELECT ba_event_id, ba_id, FROM_UNIXTIME(start_time) as start_time, first_level, FROM_UNIXTIME(end_time) as end_time, status, in_downtime FROM mod_bam_reporting_ba_events;
+-------------+-------+---------------------+-------------+---------------------+--------+-------------+
| ba_event_id | ba_id | start_time | first_level | end_time | status | in_downtime |
+-------------+-------+---------------------+-------------+--------------------- …
=> enh(bam): fix some race in bam_reporting_relations_kpi_ba_events...(20.04)

test/CMakeLists.txt
We cannot at the moment change our cmake version to cmake3. So we force the release version of google-test to an older one.
No impact in production.
=> fix(tests): Here is a hack because we cannot use cmake3 for now

core/src/processing/failover.cc
remove some too big waits
stop centengine and cbd
restart centengine using: 
systemctl start centengine
look how long it take too stop it again : 
time systemctl stop centengine
It should take less than 2 seconds...
=> fix(failover): try to not wait too long when we shutdown the failover

core/src/misc/filesystem.cc
fix(misc): xfs readdir does not fill d_type for DT_REG.
This fix a broker loading issue on xfs filesystem.
Run broker on xfs, if it works, all works
=> fix(misc): xfs readdir does not fill d_type for DT_REG.

rrd/src/lib.cc, rrd/src/output.cc, storage/src/conflict_manager.cc, storage/src/conflict_manager_storage.cc, storage/src/rebuilder.cc
If you rebuild a metric it may not be rebuilt in the following cases:
* the metric is not of type GAUGE
* the metric changed of type just before the rebuild.
=> fix(rrd): rebuild when type is not GAUGE is fixed

doc/release_notes/broker20.04.rst, storage/src/parser.cc, storage/test/perfdata.cc
Parsing a perfdata with '\r' crashed.
It is fixed.
=> fix(storage): Regression in the perfdata parsing.

core/src/mysql.cc
When connection to database is lost, connections to it should not commit any result, this cannot be done!
=> fix(core): segfault fixed when mariadb is interrupted

bam/src/configuration/reader_v2.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, doc/en/release_notes/broker20.04.rst
If a connection is in error, it must be thrown away once all the mysql objects
have been restored. So the manager don't have to give it to a new mysql object.
This patch contains also a fix in mysql_connection concerning server errors in
case of queries returning a value.
And a little improvement in reader_v2, that does not use any more stringstream,
replaced by fmt::format.
=> fix(bam): should not give a connection with error to a mysql object

core/inc/com/centreon/broker/misc/string.hh, core/src/misc/string.cc, core/test/misc/string.cc, neb/src/callbacks.cc, storage/src/conflict_manager_sql.cc
Splitting an utf-8 string needs to be careful with characters encoded on more than 1 byte.
=> Mon 5900 encoding last bug

storage/src/conflict_manager_sql.cc
On host downtimes insertion, we can have deadlocks in the database.
=> fix(storage): dead lock on host downtime insertion fixed

core/inc/com/centreon/broker/processing/feeder.hh, core/inc/com/centreon/broker/processing/stat_visitable.hh, core/src/processing/acceptor.cc, core/src/processing/feeder.cc
If you restart the Map Server, it is connected to centreon-broker, but the fixed bug here is that broker kept the previous connection to the map server. And that each time, the server was restarted...
=> Mon 6185 map duplicated connections

core/src/log_v2.cc
With log_v2, core ways always at level "trace". Now, by default it is at level "info" and can be changed as the others.
=> fix(log_v2): when log_v2 is enabled, core is at info level by default

core/inc/com/centreon/broker/pool.hh, core/src/main.cc, core/src/pool.cc, core/src/stats/helper.cc
Broker statistics have a new field containing the number of threads in the pool and also its latency in ms.
Start Broker and look at its statistics.
=> Mon 6243 pool latency

CMakeLists.txt, core/inc/com/centreon/broker/file/splitter.hh, core/inc/com/centreon/broker/file/stream.hh, core/src/file/splitter.cc, core/src/file/stream.cc, core/test/file/splitter/concurrent.cc
splitter should be much more faster.
=> Mon 6282 retention too slow

doc/en/release_notes/broker20.04.rst, tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/tcp_connection.cc, tcp/test/acceptor.cc
When there are a lot of RRD retention, Broker can have difficulties to push events to rrd broker.
This patch fixes this issue and several others.
=> Mon 6367 ipv4 bad flush 20.04.x

doc/en/release_notes/20.10.rst, tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/tcp_connection.cc, tcp/test/acceptor.cc
TCP streams should be faster to play retention files now.
=> Mon 6367 ipv4 bad flush 20.10.x

bam/inc/com/centreon/broker/bam/monitoring_stream.hh, bam/src/availability_thread.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, core/inc/com/centreon/broker/database/mysql_error.hh, core/inc/com/centreon/broker/database/mysql_task.hh, core/inc/com/centreon/broker/mysql.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql.cc, core/src/mysql_connection.cc, doc/en/release_notes/20.10.rst, sql/src/cleanup.cc, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/rebuilder.cc
In availabilities computation, durations can be doubled. Here is a fix.
This patch also improves the errors management in the mysql driver. We do not copy anymore error message strings.
=> Mon 6397 bam reporting double duration 20.10

CMakeLists.txt, bam/inc/com/centreon/broker/bam/dimension_timeperiod.hh, bam/inc/com/centreon/broker/bam/dimension_truncate_table_signal.hh, bam/inc/com/centreon/broker/bam/reporting_stream.hh, bam/src/configuration/reader_v2.cc, bam/src/dimension_timeperiod.cc, bam/src/dimension_truncate_table_signal.cc, bam/src/reporting_stream.cc
There were two bugs here :
* a mutex lock misplaced, so we truncated a table used by another thread at the same time.
* When reporting is rebuilt, if a query fails, all the following are were not executed.
REFS: MON-6397
=> fix(bam): bam reporting may conflict during rebuild

bam/inc/com/centreon/broker/bam/dimension_truncate_table_signal.hh, bam/inc/com/centreon/broker/bam/reporting_stream.hh, bam/src/availability_thread.cc, bam/src/configuration/reader.cc, bam/src/configuration/reader_v2.cc, bam/src/dimension_truncate_table_signal.cc, bam/src/reporting_stream.cc
Bam reporting durations can be doubled, this is fixed.
Database error management is improved so that when a query fails, it has a minimal impact on the following ones.
REFS: MON-6397
=> fix(bam): bam reporting conflicts 19.10

storage/src/conflict_manager_sql.cc
A little fix to avoid deadlock with comments on centreon_storage database.
REFS: MON-6506
=> fix(storage): comments queries may deadlock.

doc/en/release_notes/broker20.04.rst, storage/src/conflict_manager_sql.cc
It was possible to have a deadlock on centreon_storage database during comments insertions.
REFS: MON-6506
=> Mon 6506 comments deadlock 20.04

core/src/processing/acceptor.cc, doc/en/release_notes/20.10.rst, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/server.py
Sometimes with bad connections or because of others explanations, we can see cbd/centengine unable to connect to another cbd/engine with many CLOSE_WAIT on the acceptor side. This patch fixes this.
REFS: MON-6505
=> fix(processing): acceptor should not wait too long if a connection is available 20.10

core/src/processing/acceptor.cc, doc/en/release_notes/broker20.04.rst, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/server.py
Sometimes with bad connections or because of others explanations, we can see cbd/centengine unable to connect to another cbd/engine with many CLOSE_WAIT on the acceptor side. This patch fixes this.
REFS: MON-6505
=> fix(processing): acceptor should not wait too long if a connection is available 20.04

core/src/processing/acceptor.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/server.py
Sometimes with bad connections or because of others explanations, we can see cbd/centengine unable to connect to another cbd/engine with many CLOSE_WAIT on the acceptor side. This patch fixes this.
REFS: MON-6505
=> fix(processing): acceptor should not wait too long if a connection is available

core/inc/com/centreon/broker/config/applier/endpoint.hh, core/inc/com/centreon/broker/config/applier/init.hh, core/inc/com/centreon/broker/log_v2.hh, core/inc/com/centreon/broker/multiplexing/engine.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/inc/com/centreon/broker/mysql_manager.hh, core/inc/com/centreon/broker/processing/failover.hh, core/src/broker_impl.cc, core/src/config/applier/endpoint.cc, core/src/config/applier/init.cc, core/src/log_v2.cc, core/src/main.cc, core/src/multiplexing/engine.cc, core/src/mysql_connection.cc, core/src/mysql_manager.cc, core/src/processing/failover.cc, core/test/config/parser.cc, doc/en/release_notes/20.10.rst, lua/src/broker_utils.cc, lua/src/stream.cc, sql/src/connector.cc, sql/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager.cc, storage/src/rebuilder.cc, storage/src/stream.cc
This patch corrects many issues when Broker is badly configured and we want to stop it.
This patch also fixes the storage rebuilder mechanism.
REFS: MON-6369 ; MON-4952
=> Mon 6369 broker hangs alone 20.10

core/inc/com/centreon/broker/io/events.hh, core/test/bbdo/category.cc, test/CMakeLists.txt
We the correlation module was removed, we accidentally changed categories numbers. This patch fixes them and is completed with a test.
=> Mon 6785 bbdo categories

CHANGELOG.md, lua/CMakeLists.txt, lua/src/broker_utils.cc, lua/test/lua.cc, sql/inc/com/centreon/broker/sql/stream.hh, storage/inc/com/centreon/broker/storage/parser.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/parser.cc, storage/test/perfdata.cc
* insertion of perfdata in database more robust. Values can be NaN or Inf. In that case, a NULL value is inserted instead.
* when the perfdata parser fails, it logs an error with the (host_id,service_id) of the associated service so it is easier for user to debug his checks.
* the streamconnector provides a new function broker.md5(str) that returns the md5 sum of the string str.
REFS: MON-6915 MON-6918
=> enh(storage): insertion of perfdata more robust and logs more verbose

CHANGELOG.md, lua/CMakeLists.txt, lua/src/broker_utils.cc, lua/test/lua.cc, sql/inc/com/centreon/broker/sql/stream.hh, storage/inc/com/centreon/broker/storage/parser.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/parser.cc, storage/test/perfdata.cc
* insertion of perfdata in database more robust. Values can be NaN or Inf. In that case, a NULL value is inserted instead.
* when the perfdata parser fails, it logs an error with the (host_id,service_id) of the associated service so it is easier for user to debug his checks.
* the streamconnector provides a new function broker.md5(str) that returns the md5 sum of the string str.
REFS: MON-6915 MON-6918
=> Mon 6915 log details metrics insertion 20.10

CMakeLists.txt, lua/CMakeLists.txt, lua/src/broker_utils.cc, lua/test/lua.cc, sql/inc/com/centreon/broker/sql/stream.hh, storage/inc/com/centreon/broker/storage/parser.hh, storage/inc/com/centreon/broker/storage/stream.hh, storage/src/conflict_manager_sql.cc, storage/src/conflict_manager_storage.cc, storage/src/parser.cc, storage/test/perfdata.cc
* insertion of perfdata in database more robust. Values can be NaN or Inf. In that case, a NULL value is inserted instead.
* when the perfdata parser fails, it logs an error with the (host_id,service_id) of the associated service so it is easier for user to debug his checks.
* the streamconnector provides a new function broker.md5(str) that returns the md5 sum of the string str.
REFS: MON-6915 MON-6918
=> fix(storage/lua): perfdata insertion more robust and logs more verbose

core/src/compression/stream.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/client-no-nego.py
Sometimes, connector closes connections but acceptor keeps them. This leads to CLOSE_WAIT states. This patch fixes this issue.
REFS: MON-6393
=> Mon 6393 close wait

CHANGELOG.md, core/src/compression/stream.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/client-no-nego.py
Sometimes, connector closes connections but acceptor keeps them. This leads to CLOSE_WAIT states. This patch fixes this issue.
REFS: MON-6393
=> Mon 6393 close wait 20.10

CHANGELOG.md, core/inc/com/centreon/broker/mapping/entry.hh, core/src/compression/stream.cc, core/src/mapping/entry.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/client-no-nego.py
When centengine is shutdown, we often can remark a segfault due to a bad allocation made in the bbdo manager.
This PR fixes the issue.
REFS: MON-5939
=> Mon 5939 dangling pointer cbd 20.10

CHANGELOG.md, core/src/compression/stream.cc, core/src/mapping/entry.cc, tcp/inc/com/centreon/broker/tcp/tcp_async.hh, tcp/src/tcp_async.cc, test/python/client-no-nego.py
Sometimes, connector closes connections but acceptor keeps them. This leads to CLOSE_WAIT states. This patch fixes this issue.
REFS: MON-6393
=> Mon 6393 close wait 20.04

core/inc/com/centreon/broker/mapping/entry.hh, core/src/mapping/entry.cc
When centengine is shutdown, we often can remark a seffault due to a bad allocation made in the bbdo manager.
This PR fixes the issue.
REFS: MON-5939
=> fix(entry): bad memory allocation

CHANGELOG.md, core/inc/com/centreon/broker/mapping/entry.hh, core/src/mapping/entry.cc, tcp/src/tcp_async.cc
When centengine is shutdown, we often can remark a segfault due to a bad allocation made in the bbdo manager.
This PR fixes the issue.
REFS: MON-5939
=> fix(entry): memory leak fixed and code simplified.

core/src/bbdo/acceptor.cc, core/src/bbdo/connector.cc
The bug concerning the factory is not fixed for now.
But no more connections are stacked.
REFS: MON-7135
=> fix(bbdo): memory leak on tcp::streams

CHANGELOG.md, core/src/misc/string.cc, core/test/misc/string.cc
The escape string function had a bug. Here is a fix.
REFS: MON-7021
=> Mon 7021 escape string 20.04.x

storage/src/conflict_manager_sql.cc
When Broker restart, it purges downtimes and comments by executing following requests :
```
"UPDATE comments AS c JOIN hosts AS h ON c.host_id=h.host_id SET c.deletion_time=1617947929 WHERE h.instance_id=3 AND c.persistent=0 AND (c.deletion_time IS NULL OR c.deletion_time=0)
UPDATE downtimes AS d INNER JOIN hosts AS h ON d.host_id=h.host_id SET d.cancelled=1 WHERE d.actual_end_timNULL AND d.cancelled=0 AND h.instance_id=3"
```
If there are thousands of downtimes and comments, this can be problematic and takes few seconds/minutes to execute. (It can happen cause some customer don’t purge those tables)
Those queries could be optimized by removing JOIN with hosts cause instance_id column exist in downtimes & comments table.
cf (https://centreon.atlassian.net/browse/MON-7026).
How to test
* …
=> enh(storage): remove useless join in sql query

CHANGELOG.md, CMakeLists.txt, bam/CMakeLists.txt, cmake.sh, conanfile.txt, correlation/CMakeLists.txt, graphite/CMakeLists.txt, influxdb/CMakeLists.txt, lua/CMakeLists.txt, neb/CMakeLists.txt, rrd/CMakeLists.txt, simu/CMakeLists.txt, sql/CMakeLists.txt, stats/CMakeLists.txt, storage/CMakeLists.txt, tcp/CMakeLists.txt, test/CMakeLists.txt, tls/CMakeLists.txt, watchdog/CMakeLists.txt
Broker 20.10 can be compiled now using conan-center packages.
On centos7, we need devtoolset-9.
REFS: MON-7244
=> Using conan center 20.10

storage/test/perfdata.cc, tcp/src/tcp_async.cc
A patch to simplify the connection between central and pollers.
REFS: MON-7355
=> Mon 7355 connection failed

core/inc/com/centreon/broker/misc/string.hh, core/src/misc/string.cc, core/src/time/timerange.cc, core/test/time/timerange.cc, test/CMakeLists.txt
Timeranges of timeperiods can't be parsed if they end with \r or \n. Now its possible.
=> Mon 7176 timerange parsing

tls/src/params.cc
GnuTLS query not understood on Centos8/Redhat8
REFS: MON-7398
=> Mon 7398 tls query

CHANGELOG.md, tls/src/params.cc
GnuTLS query not understood on centos8/RedHat8.
REFS: MON-7398
=> Mon 7398 tls query 21.04

CHANGELOG.md, tls/src/params.cc
TLS query was not understood on Centos8/Redhat 8
REFS: MON-7398
=> Mon 7398 tls query 20.04

CHANGELOG.md, tcp/src/tcp_connection.cc
when cbd is restarted, centengine can enter in an infinite loop instead of trying to reconnect.
REFS: MON-7373
=> Mon 7373 engine reco 21.04

CHANGELOG.md, core/inc/com/centreon/broker/log_v2.hh, core/src/log_v2.cc, core/test/rpc/brokerrpc.cc, influxdb/inc/com/centreon/broker/influxdb/influxdb12.hh, influxdb/src/influxdb12.cc, lua/src/broker_socket.cc, tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/src/tcp_connection.cc
Getting the remote endpoint from a socket is implemented in two ways:
* a method returning an exception on failure
* a method with an error_code as parameter that the caller must check.
In our code, we called the first one but did not catch the eventual exception.
REFS: MON-6904
=> fix(tcp): getting a remote endpoint from a socket may fail

CHANGELOG.md, core/inc/com/centreon/broker/log_v2.hh, core/src/log_v2.cc, core/test/rpc/brokerrpc.cc, influxdb/inc/com/centreon/broker/influxdb/influxdb12.hh, influxdb/src/influxdb12.cc, lua/src/broker_socket.cc, tcp/inc/com/centreon/broker/tcp/tcp_connection.hh, tcp/src/acceptor.cc, tcp/src/connector.cc, tcp/src/stream.cc, tcp/src/tcp_async.cc, tcp/src/tcp_connection.cc
Getting the remote endpoint from a socket is implemented in two ways:
* a method returning an exception on failure
* a method with an error_code as parameter that the caller must check.
In our code, we called the first one but did not catch the eventual exception.
REFS: MON-6904
=> fix(tcp): getting remote endpoint from a socket may fail

CHANGELOG.md, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc, core/src/mysql_manager.cc
This is useful to give an operational connection and not one already
disconnected.
REFS: MON-6917
=> Mon 6917 server has gone away 20.10

CHANGELOG.md, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc, core/src/mysql_manager.cc, stats/test/stats.cc
This is useful to give an operational connection and not one already
disconnected.
REFS: MON-6917
=> fix(mysql): New method mysql_connection::ping()

bam/inc/com/centreon/broker/bam/ba_duration_event.hh, bam/inc/com/centreon/broker/bam/kpi_event.hh, bam/src/ba.cc, bam/src/ba_duration_event.cc, bam/src/configuration/applier/ba.cc, bam/src/configuration/kpi.cc, bam/src/configuration/reader_v2.cc, bam/src/kpi.cc, bam/src/kpi_ba.cc, bam/src/kpi_boolexp.cc, bam/src/kpi_event.cc, bam/src/kpi_service.cc, bam/src/main.cc, bam/src/monitoring_stream.cc, bam/src/reporting_stream.cc, bam/src/service_book.cc, bam/test/ba/kpi_ba.cc, bam/test/ba/kpi_service.cc, bam/test/exp_builder/availability_builder.cc, cmake.sh, core/inc/com/centreon/broker/bbdo/version_response.hh, core/inc/com/centreon/broker/io/extension.hh, core/test/test_server.cc, notification/src/stream.cc, sql/src/stream.cc, storage/src/conflict_manager_sql.cc, tcp/src/tcp_async.cc
New BA with new KPI have their start time badly initialized. This patch fixes this issue.
REFS: MON-7405
=> fix(bam): when a new ba is created, start_time is correctly initialized.

Jenkinsfile
Retrieve quality gate status with sonar api and listening to the coming webhook in order to avoid ten minutes timeout.
=> fix(ci):quality gate timeout management

CHANGELOG.md, lua/test/lua.cc, neb/CMakeLists.txt, neb/src/neb.cc, neb/src/service_status.cc
A link issue in cbmod creates segfault in centengine.
This patch fixes this issue.
REFS: MON-10682
=> Mon 10682 engine segfault 20.10

core/src/bbdo/acceptor.cc
When an output is configured with a reversed connection, if started
with no peer, we cannot stop it.
REFS: MON-10888
=> fix(bbdo): A stop condition was missing in bbdo acceptor.

core/inc/com/centreon/broker/mysql.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc, core/src/mysql_manager.cc
This patch fixes the "MySQL server has gone away" we can see in the cbd logs.
REFS: MON-6917
=> fix(sql): Before executing a bulk of queries, we check db connection

CHANGELOG.md, core/src/mysql_connection.cc
When a connection received from the DB server "mysql server has gone away", it tries to reconnect, this avoid many errors, paritularly those with bam availabilities computations.
REFS: MON-6917
=> Mon 6917 dabase reconnect 20.04

CHANGELOG.md, core/inc/com/centreon/broker/mysql.hh, core/inc/com/centreon/broker/mysql_connection.hh, core/src/mysql_connection.cc, core/src/mysql_manager.cc
This patch fixes the "MySQL server has gone away" we can see in the cbd logs.
REFS: MON-6917
=> Mon 6917 dabase reconnect 20.10

CHANGELOG.md, core/src/processing/failover.cc, core/src/processing/feeder.cc
Some try/catch forgotten around the strem::stop() method.
REFS: MON-10922
=> Mon 10922 stop segfault 21.04

core/src/processing/failover.cc, core/src/processing/feeder.cc
Some try/catch forgotten around the strem::stop() method.
REFS: MON-10922
=> fix(processing): stop() calls must be protected by try/catch

Jenkinsfile
For hotfixes or testing purpose, we need to retrieve rpm packages from Jenkins. Here's the enhancement doing it.
Launch jenkins job on this PR and retrieve this kind of view :
=> enh(ci): add rpms as jenkins artifacts

Jenkinsfile
Remove output rpm directory after stashing and archiving it because it could push twice the same rpms if it's not clean.
Check in the jenkins workspace that the output directory doesn't exist after the package stage
=> fix(ci): removing output directory

.gitignore, CHANGELOG.md, core/inc/com/centreon/broker/database/mysql_error.hh, core/inc/com/centreon/broker/mapping/property.hh, core/inc/com/centreon/broker/processing/acceptor.hh, core/inc/com/centreon/broker/processing/endpoint.hh, core/inc/com/centreon/broker/processing/failover.hh, core/src/bbdo/stream.cc, core/src/mysql_manager.cc, core/src/pool.cc, lua/src/broker_event.cc, lua/src/broker_utils.cc, simu/docker/lua/neb/services.lua, sql/inc/com/centreon/broker/sql/stream.hh, sql/src/cleanup.cc, sql/src/stream.cc, storage/inc/com/centreon/broker/storage/conflict_manager.hh, storage/inc/com/centreon/broker/storage/parser.hh, storage/inc/com/centreon/broker/storage/rebuild.hh, storage/inc/com/centreon/broker/storage/rebuilder.hh, storage/src/conflict_manager.cc, storage/src/conflict_manager_sql.cc
Transverse tables have their queries working on only one connection now. Each one its connection.
REFS: MON-10735
=> fix(conflict_manager): hostgroups conflicts should be fixed.

tcp/src/tcp_async.cc
For some configurations, when the connection is lost, the acceptor does not detect it. We add a keepalive to solve this point.
REFS: MON-11121
=> fix(tcp): attempt to add a keep alive on the acceptor side

CHANGELOG.md, tcp/src/tcp_async.cc
For some configurations, when the connection is lost, the acceptor does not detect it. We add a keepalive to solve this point.
REFS: MON-11121
=> Mon 11121 keep alive acceptor 20.10

CHANGELOG.md, tcp/src/tcp_async.cc
For some configurations, when the connection is lost, the acceptor does not detect it. We add a keepalive to solve this point.
REFS: MON-11121
=> fix(tcp): We add a keepalive on the acceptor side.

CHANGELOG.md, core/inc/com/centreon/broker/bbdo/stream.hh, core/src/bbdo/stream.cc, core/src/multiplexing/muxer.cc, core/test/multiplexing/muxer/read.cc, tcp/src/tcp_connection.cc
Fix in tcp_connectionn::flush() to solve a lock.
REFS: MON-11163
=> Mon 11163 flush hang 21.04

CHANGELOG.md, tcp/src/tcp_connection.cc
fix in tcp_connection::flush() to avoid lock.
REFS: MON-11163
=>  fix(tcp): flush() function can get stuck.

CHANGELOG.md, tcp/src/tcp_connection.cc
Fix in tcp_connection::flush()  to avoid lock.
REFS: MON-11163
=> fix(tcp): flush() function can get stuck.

CHANGELOG.md, core/src/bbdo/stream.cc
If a broker receives bbdo message it cannot unserialize because of a missing    
module, it must be able to acknowledge it. Otherwise, this message is kept      
in retention by the peer and this can lead cbd instances to get stuck.
REFS: MON-11162
=> Mon 11162 bam rrd 21.04

core/src/bbdo/stream.cc
If a broker receives bbdo message it cannot unserialize because of a missing    
module, it must be able to acknowledge it. Otherwise, this message is kept      
in retention by the peer and this can lead cbd instances to get stuck. 
REFS: MON-11162
=> fix(bbdo): real bbdo events we can not unserialize are acknowledged

CHANGELOG.md, bam/src/ba.cc
bad initialization of ba in best status: they are always in state OK.
REFS: MON-11430
=> fix(bam): the soft state should be updated too.

CHANGELOG.md, bam/src/ba.cc
When a ba in best status is initialized, it is always in state OK.
REFS: MON-11430
=> fix(bam): bad initialization of ba in best status

CHANGELOG.md, core/src/mysql_connection.cc
mysql_ping called with a timeout and less often.
REFS: MON-11530
=> fix(mysql_connection): mysql_ping is called with a timeout.
